### ISSUE TITLE
brainfock.org expired(?) so all links to it are invalid

### ISSUE THREAD

**Issue by ghost** [Brainfock/Brainfock#9]

**Comment by Webkadabra** [comment]
@noformnocontent actually only my DigitalOcean account has expired that hosted the DEMO, I think that redirect is because of DNS setting (I will fix brainfock.org to redirect to github repo). I would love to get demo server up and running, if  somebody could provide a host/vps for demo servers, we'd be online!

**Comment by ghost** [comment]
i would suggest use [GoMix](https://gomix.com/help/faqs/) ("HyperDev" before not too long ago) for now, since it's free and has a;most the same specs cheapest DO droplet has

**Comment by Webkadabra** [comment]
@noformnocontent thanks for sharing, I'm not yet familiar with GoMix, but will try to setup demo there

**Comment by Webkadabra** [comment]
@noformnocontent I checked out GoMix, it doesn't run Brainfock. Were you able to set it up there?

**Comment by JPBlancoDB** [comment]
you can use heroku
https://www.heroku.com/

**Comment by Webkadabra** [comment]
@JPBlancoDB I couldn't set it up there, Heroku is asking for CC number :laughing: If I'd have valid CC I'd probably pay for that Digitalocean demo server we had haha
